name: Test on MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bazel:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - run: brew install cppunit
      - run: bazel test -s
